### ISSUE TITLE
Error in setDataSource

### ISSUE THREAD

**Issue by MrDoshman** [harmonoid/flutter_media_metadata#16]
When I use the following code, the continuation of the code stops without any error
`await MetadataRetriever.fromFile(File(songInfo.filePath));`

I tried to find the library problem to fix it
![image](https://user-images.githubusercontent.com/48115957/131585566-53ef94f5-ba90-4762-b7b6-7dd88d4c3188.png)
I noticed that an error occurs when using setFilePath (`retriever.setFilePath(filePath);`)
![image](https://user-images.githubusercontent.com/48115957/131585731-f498dbf1-d516-4562-b8be-8eb8dec555f9.png)
This function gives **java.lang.IllegalArgumentException** error without any message

**Comment by alexmercerind** [comment]
Could you show what argument are you actually passing? Without it I cannot tell what is wrong.

https://github.com/harmonoid/flutter_media_metadata/blob/f7773003d97d6310f6aebf2d76bd6a19a65e6955/example/android/app/src/main/AndroidManifest.xml#L11

You might wanna use legacy storage access if you are using API 30+. I'm not much Android expert.

**Comment by MrDoshman** [comment]
https://user-images.githubusercontent.com/48115957/131708947-ccb21eb6-e7a2-433f-a6da-240359636263.mp4

This video shows the problem.
I used to use this library but now it does not work. I tried to use the previous versions but it did not work

**Comment by MrDoshman** [comment]
I did not try android: `requestLegacyExternalStorage="true"` because I am using Android 10 (API 29).
But now I tried and it worked for me.
Thank you very much, my problem was solved. But I don't know why I did not have this problem before
