### ISSUE TITLE
Add iOS support

### ISSUE THREAD

**Issue by alexmercerind** [harmonoid/flutter_media_metadata#3]
I don't own a mac or an iOS device.

There are some people out there, who wanna use this plugin on iOS devices.

Any Objective-C or Swift geek is free to add iOS support to this plugin.

Thanks.
My appreciation, if you decide to help out.

**Comment by mohammadne** [comment]
Any Objective-C or Swift geek to progress this awesome package ?

**Comment by DiscombobulatedDrag** [comment]
I added iOS support.
https://github.com/DiscombobulatedDrag/flutter_media_metadata/commit/b281ef82e4c7c7c7183818ea55edcc2f3af9c169

Limitations
- Get writer name does not support. (ID3 Tag)
- Get bitrate possibly supports CBR only. (VBR encoded file returns average bitrate)
- iOS example app does not support real devices.(If you try iOS example app, you must copy the music file to the simulator directory)

**Comment by alexmercerind** [comment]
Published v0.1.2, arriving with iOS support, big thanks to @DiscombobulatedDrag.
